# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c2s_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rc2s_msg.proto\x12\x06\x63s.msg\"\x1d\n\x0c\x43\x32SPlayCards\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\r\".\n\x08S2CDoBid\x12\x0f\n\x07seat_id\x18\x01 \x01(\r\x12\x11\n\tbid_score\x18\x02 \x01(\r\"A\n\rS2CDoRedouble\x12\x0f\n\x07seat_id\x18\x01 \x01(\r\x12\r\n\x05score\x18\x02 \x01(\r\x12\x10\n\x08multiple\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c2s_msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals["_C2SPLAYCARDS"]._serialized_start=25
  _globals["_C2SPLAYCARDS"]._serialized_end=54
  _globals["_S2CDOBID"]._serialized_start=56
  _globals["_S2CDOBID"]._serialized_end=102
  _globals["_S2CDOREDOUBLE"]._serialized_start=104
  _globals["_S2CDOREDOUBLE"]._serialized_end=169
# @@protoc_insertion_point(module_scope)
